import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import api from "../api/axios";
import VitalTrendChart from "../components/VitalTrendChart";
import type { Vital } from "../components/VitalTrendChart";
type Patient = { id: number; name: string };
const dateTime = (value: string) => { const date = new Date(value); return [date.toLocaleDateString(), date.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" })]; };
export default function HistoryPage() { const [selected, setSelected] = useState<number>(); const { data: patients = [] } = useQuery({ queryKey: ["patients"], queryFn: () => api.get("/api/patients/").then(r => r.data as Patient[]) }); const id = selected ?? patients[0]?.id; const { data: readings = [] } = useQuery({ queryKey: ["history", id], enabled: !!id, queryFn: () => api.get(`/api/vitals/${id}?limit=100`).then(r => r.data as Vital[]) }); const exportCsv = () => { const rows = ["Date,Time,Heart rate (bpm),Oxygen level (%),Temperature (°C)", ...readings.map(v => { const [date, time] = dateTime(v.recorded_at); return `${date},${time},${v.heart_rate},${v.spo2},${v.temperature}`; })]; const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([rows.join("\n")], { type: "text/csv" })); link.download = "patient-history.csv"; link.click(); }; return <><header className="page-head"><div><h1>Patient history</h1><p>Review recorded readings by date and time.</p></div><button className="button secondary" onClick={exportCsv}>Export CSV</button></header><div className="dashboard-picker"><label>Patient <select value={id ?? ""} onChange={e => setSelected(Number(e.target.value))}>{patients.map(p => <option key={p.id} value={p.id}>ID #{p.id} · {p.name}</option>)}</select></label></div><section className="panel"><h2>Vital sign trend</h2><VitalTrendChart data={readings}/></section><ReadingTable readings={readings}/></> }
export function ReadingTable({ readings }: { readings: Vital[] }) { return <section className="panel reading-table-panel"><h2>Recorded readings</h2><div className="table-wrap"><table><thead><tr><th>Date</th><th>Time</th><th>Heart rate</th><th>Oxygen level</th><th>Temperature</th></tr></thead><tbody>{readings.length ? readings.map((v, index) => { const [date, time] = dateTime(v.recorded_at); return <tr key={`${v.recorded_at}-${index}`}><td>{date}</td><td>{time}</td><td>{v.heart_rate} bpm</td><td>{v.spo2}%</td><td>{v.temperature} °C</td></tr>; }) : <tr><td colSpan={5} className="empty-cell">No readings are available yet.</td></tr>}</tbody></table></div></section> }
